services:
  redis:
    image: redis:7
    ports:
      - '6379:6379'
    restart: unless-stopped

  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - DATABASE_URL=${DATABASE_URL}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRES_IN=${JWT_EXPIRES_IN}
    depends_on:
      - redis
    # ports:
    #   - '3000:3000'
    restart: unless-stopped
    command: ["bun", "run", "start:prod"] 