module.exports = {
  moduleFileExtensions: ['js', 'json', 'ts'],
  rootDir: 'src',
  testRegex: '.*\\.spec\\.ts$',
  transform: {
    '^.+\\.(t|j)s$': 'ts-jest',
  },
  collectCoverageFrom: [
    '**/*.(t|j)s',
    '!**/*.spec.ts',
    '!**/*.integration.spec.ts',
    '!**/node_modules/**',
    '!**/dist/**',
    '!**/coverage/**',
    '!**/test/**',
    '!**/__tests__/**',
    '!**/jest.config.js',
    '!**/main.ts',
    '!**/index.ts',
    '!**/*.module.ts',
    '!**/*.dto.ts',
    '!**/*.entity.ts',
    '!**/*.interface.ts',
    '!**/*.type.ts',
    '!**/*.enum.ts',
    '!**/*.decorator.ts',
    '!**/*.guard.ts',
    '!**/*.filter.ts',
    '!**/*.interceptor.ts',
    '!**/*.pipe.ts',
    '!**/*.strategy.ts',
    '!**/*.middleware.ts',
    '!**/*.config.ts',
    '!**/*.config.js',
    '!**/*.config.mjs',
    '!**/common/utils/test-utils.ts',
    '!**/common/utils/type-guards.ts',
    '!**/common/types/**',
    '!**/common/interfaces/**',
    '!**/common/filters/**',
    '!**/common/guards/**',
    '!**/common/interceptors/**',
    '!**/common/pipes/**',
    '!**/common/strategies/**',
    '!**/common/decorators/**',
    '!**/common/middleware/**',
    '!**/common/config/**',
  ],
  coverageDirectory: '../coverage',
  coverageReporters: ['text', 'lcov', 'html', 'json'],
  coverageThreshold: {
    global: {
      branches: 80,
      functions: 80,
      lines: 80,
      statements: 80,
    },
  },
  testEnvironment: 'node',
  setupFilesAfterEnv: ['<rootDir>/../jest.setup.js'],
  moduleNameMapper: {
    '^@/(.*)$': '<rootDir>/$1',
    '^@common/(.*)$': '<rootDir>/common/$1',
    '^@users/(.*)$': '<rootDir>/users/$1',
    '^@property/(.*)$': '<rootDir>/property/$1',
    '^@message/(.*)$': '<rootDir>/message/$1',
    '^@favorite/(.*)$': '<rootDir>/favorite/$1',
    '^@wishlist/(.*)$': '<rootDir>/wishlist/$1',
    '^@auth/(.*)$': '<rootDir>/auth/$1',
    '^@redis/(.*)$': '<rootDir>/redis/$1',
  },
  testTimeout: 30000,
  verbose: true,
  detectOpenHandles: true,
  forceExit: true,
};